on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

name: live-integration

jobs:
  live-integration:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RIRODS_LIVE: true
      R_PROFILE_USER: /dev/null
      R_ENVIRON_USER: /dev/null
      RENV_CONFIG_AUTOLOADER_ENABLED: FALSE

    steps:
      - name: Checkout rirods
        uses: actions/checkout@v3
        with:
          path: rirods

      - name: Checkout irods_demo
        uses: actions/checkout@v3
        with:
          repository: irods/irods_demo
          path: irods_demo

      - name: Setup iRODS demo
        run: |
          cd ./irods_demo
          git submodule sync --recursive
          git submodule update --init --force --recursive --remote
          docker compose up -d nginx-reverse-proxy irods-client-http-api irods-client-icommands

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./rirods
          extra-packages: any::pkgload
          needs: check

      - name: Run live integration tests
        working-directory: ./rirods
        shell: Rscript {0}
        run: |
          pkgload::load_all(".", quiet = TRUE)
          for (path in Sys.glob("tests/testthat/test-live-*.R")) {
            testthat::test_file(path, reporter = "summary")
          }
